version: '3'
services:

  #Consumer to read from Kafka queue
  consumer:
    image: consumer
    container_name: consumer
    restart: always
    environment:
      - KAFKAPORT=kafka:9093
      - TOPICNAME=test
      - ZOOKEEPERPORT=zookeeper:2181 
      - CONSUMERGROUP=consumerGroup_1
    ports:
      - "5001:5001"
    networks:
      - full_app_dockerNet 
        # To ensure that the containers in different docker-compose files communicate with each other, we place them on the same network. The complete network name is 'zookeeper_dockerNet'. It is derived by joining the name of the folder from which the network originates (i.e., zookeeper) and the name of the network (i.e., dockerNet).

networks:
  full_app_dockerNet:
    external: true #Label the other docker-compose network as an external network to the current docker-compose file
